#!/usr/bin/env sh
set -eu

PROJECT_ROOT_DIR=$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)
TARGET_FILE="${PROJECT_ROOT_DIR}/internal/adapters/handler/cli/mock_task_service.go"
SQLITE_GENERATED_DIR="${PROJECT_ROOT_DIR}/internal/adapters/repository/sqlite/generated"
OUTPUT_FILE=$(mktemp "${TMPDIR:-/tmp}/go-generate-test.XXXXXX")
GOCACHE_DIR=$(mktemp -d "${TMPDIR:-/tmp}/go-generate-cache.XXXXXX")
BACKUP_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/go-generate-backup.XXXXXX")
BACKUP_MOCKS_DIR="${BACKUP_ROOT}/mocks"
BACKUP_SQLITE_DIR="${BACKUP_ROOT}/sqlite-generated"
MOCK_LIST_FILE="${BACKUP_ROOT}/mock-files.txt"
SQLITE_GENERATED_EXISTS=0

mkdir -p "${BACKUP_MOCKS_DIR}"

cleanup() {
	find "${PROJECT_ROOT_DIR}" -type f -name 'mock_*.go' -delete

	if [ -f "${MOCK_LIST_FILE}" ]; then
		while IFS= read -r relative_path; do
			source_path="${BACKUP_MOCKS_DIR}/${relative_path}"
			target_path="${PROJECT_ROOT_DIR}/${relative_path}"
			mkdir -p "$(dirname "${target_path}")"
			cp "${source_path}" "${target_path}"
		done < "${MOCK_LIST_FILE}"
	fi

	rm -rf "${SQLITE_GENERATED_DIR}"
	if [ "${SQLITE_GENERATED_EXISTS}" -eq 1 ]; then
		cp -R "${BACKUP_SQLITE_DIR}" "${SQLITE_GENERATED_DIR}"
	fi

	rm -f "${OUTPUT_FILE}"
	rm -rf "${GOCACHE_DIR}"
	rm -rf "${BACKUP_ROOT}"
}

trap cleanup EXIT INT TERM

find "${PROJECT_ROOT_DIR}" -type f -name 'mock_*.go' | while IFS= read -r mock_file; do
	relative_path=${mock_file#"${PROJECT_ROOT_DIR}/"}
	backup_path="${BACKUP_MOCKS_DIR}/${relative_path}"
	mkdir -p "$(dirname "${backup_path}")"
	cp "${mock_file}" "${backup_path}"
	printf '%s\n' "${relative_path}" >> "${MOCK_LIST_FILE}"
done

if [ -d "${SQLITE_GENERATED_DIR}" ]; then
	SQLITE_GENERATED_EXISTS=1
	cp -R "${SQLITE_GENERATED_DIR}" "${BACKUP_SQLITE_DIR}"
fi

cat > "${TARGET_FILE}" <<'EOF'
// Code generated by mockery. DO NOT EDIT.

package cli

import (
	agentcore "agent/internal/core"
)

type MockTaskService struct {
	agentcore.TaskService
}
EOF

cd "${PROJECT_ROOT_DIR}"

if GOCACHE="${GOCACHE_DIR}" ./scripts/generate/go.sh >"${OUTPUT_FILE}" 2>&1; then
	if grep -q 'agent/internal/core' "${TARGET_FILE}"; then
		printf 'expected stale mock import to be replaced, but it was still present\n' >&2
		cat "${OUTPUT_FILE}" >&2
		exit 1
	fi
	if ! grep -q 'rig/internal/core' "${TARGET_FILE}"; then
		printf 'expected regenerated mock to import rig/internal/core\n' >&2
		cat "${OUTPUT_FILE}" >&2
		exit 1
	fi
	exit 0
fi

printf 'go generate script failed:\n' >&2
cat "${OUTPUT_FILE}" >&2
exit 1
