version: 2

before:
  hooks:
    - make generate

builds:
  - main: ./cmd/agent
    binary: agent
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: BaronBonet
    name: tmux-llm
