version: 2

before:
  hooks:
    - make generate

builds:
  - main: ./cmd/rig
    binary: rig
    ldflags:
      - -s -w -X main.version={{ .Tag }}
      - -X rig/internal/adapters/taskdaemon.currentFrontendBuildVersion={{ .Tag }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    formats: tar.gz

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  mode: keep-existing
  github:
    owner: BaronBonet
    name: rig
