packages:
  agent/internal/core:
    config:
      filename: mock_{{ snakecase .InterfaceName }}.go
      mockname: Mock{{.InterfaceName}}
      inpackage: true
      resolve-type-alias: false
      disable-version-string: true
      issue-845-fix: true
      with-expecter: true
      all: false
      recursive: false
      dir: "{{ .InterfaceDirRelative }}"
    interfaces:
      TaskRepository:
      RepoConfigRepository:
      WorkspaceSeeder:
      RepoClient:
      SessionClient:
      RuntimeMonitor:
      ProviderClient:
  agent/internal/adapters/handler/cli:
    config:
      filename: mock_{{ snakecase .InterfaceName }}.go
      mockname: Mock{{.InterfaceName}}
      inpackage: true
      resolve-type-alias: false
      disable-version-string: true
      issue-845-fix: true
      with-expecter: true
      all: false
      recursive: false
      dir: "{{ .InterfaceDirRelative }}"
    interfaces:
      TaskService:
  agent/internal/pkg/execx:
    config:
      filename: mock_{{ snakecase .InterfaceName }}.go
      mockname: Mock{{.InterfaceName}}
      inpackage: true
      resolve-type-alias: false
      disable-version-string: true
      issue-845-fix: true
      with-expecter: true
      all: false
      recursive: false
      dir: "{{ .InterfaceDirRelative }}"
    interfaces:
      Runner:
  agent/internal/adapters/client/tmux:
    config:
      filename: mock_{{ snakecase .InterfaceName }}.go
      mockname: Mock{{.InterfaceName}}
      inpackage: true
      resolve-type-alias: false
      disable-version-string: true
      issue-845-fix: true
      with-expecter: true
      all: false
      recursive: false
      dir: "{{ .InterfaceDirRelative }}"
    interfaces:
      controlPipe:
      controlPipeFactory:
