// Code generated by mockery. DO NOT EDIT.

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWorkspaceSeeder is an autogenerated mock type for the WorkspaceSeeder type
type MockWorkspaceSeeder struct {
	mock.Mock
}

type MockWorkspaceSeeder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaceSeeder) EXPECT() *MockWorkspaceSeeder_Expecter {
	return &MockWorkspaceSeeder_Expecter{mock: &_m.Mock}
}

// SeedWorkspace provides a mock function with given fields: ctx, in, progress
func (_m *MockWorkspaceSeeder) SeedWorkspace(ctx context.Context, in SeedWorkspaceInput, progress func(string)) error {
	ret := _m.Called(ctx, in, progress)

	if len(ret) == 0 {
		panic("no return value specified for SeedWorkspace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, SeedWorkspaceInput, func(string)) error); ok {
		r0 = rf(ctx, in, progress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkspaceSeeder_SeedWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeedWorkspace'
type MockWorkspaceSeeder_SeedWorkspace_Call struct {
	*mock.Call
}

// SeedWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - in SeedWorkspaceInput
//   - progress func(string)
func (_e *MockWorkspaceSeeder_Expecter) SeedWorkspace(ctx interface{}, in interface{}, progress interface{}) *MockWorkspaceSeeder_SeedWorkspace_Call {
	return &MockWorkspaceSeeder_SeedWorkspace_Call{Call: _e.mock.On("SeedWorkspace", ctx, in, progress)}
}

func (_c *MockWorkspaceSeeder_SeedWorkspace_Call) Run(run func(ctx context.Context, in SeedWorkspaceInput, progress func(string))) *MockWorkspaceSeeder_SeedWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(SeedWorkspaceInput), args[2].(func(string)))
	})
	return _c
}

func (_c *MockWorkspaceSeeder_SeedWorkspace_Call) Return(_a0 error) *MockWorkspaceSeeder_SeedWorkspace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkspaceSeeder_SeedWorkspace_Call) RunAndReturn(run func(context.Context, SeedWorkspaceInput, func(string)) error) *MockWorkspaceSeeder_SeedWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateSeedPaths provides a mock function with given fields: ctx, repoRoot, relativePaths
func (_m *MockWorkspaceSeeder) ValidateSeedPaths(ctx context.Context, repoRoot string, relativePaths []string) error {
	ret := _m.Called(ctx, repoRoot, relativePaths)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSeedPaths")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, repoRoot, relativePaths)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkspaceSeeder_ValidateSeedPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateSeedPaths'
type MockWorkspaceSeeder_ValidateSeedPaths_Call struct {
	*mock.Call
}

// ValidateSeedPaths is a helper method to define mock.On call
//   - ctx context.Context
//   - repoRoot string
//   - relativePaths []string
func (_e *MockWorkspaceSeeder_Expecter) ValidateSeedPaths(ctx interface{}, repoRoot interface{}, relativePaths interface{}) *MockWorkspaceSeeder_ValidateSeedPaths_Call {
	return &MockWorkspaceSeeder_ValidateSeedPaths_Call{Call: _e.mock.On("ValidateSeedPaths", ctx, repoRoot, relativePaths)}
}

func (_c *MockWorkspaceSeeder_ValidateSeedPaths_Call) Run(run func(ctx context.Context, repoRoot string, relativePaths []string)) *MockWorkspaceSeeder_ValidateSeedPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockWorkspaceSeeder_ValidateSeedPaths_Call) Return(_a0 error) *MockWorkspaceSeeder_ValidateSeedPaths_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkspaceSeeder_ValidateSeedPaths_Call) RunAndReturn(run func(context.Context, string, []string) error) *MockWorkspaceSeeder_ValidateSeedPaths_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkspaceSeeder creates a new instance of MockWorkspaceSeeder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaceSeeder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaceSeeder {
	mock := &MockWorkspaceSeeder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
