// Code generated by mockery. DO NOT EDIT.

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepoConfigLoader is an autogenerated mock type for the RepoConfigLoader type
type MockRepoConfigLoader struct {
	mock.Mock
}

type MockRepoConfigLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoConfigLoader) EXPECT() *MockRepoConfigLoader_Expecter {
	return &MockRepoConfigLoader_Expecter{mock: &_m.Mock}
}

// LoadRepoConfig provides a mock function with given fields: ctx, repoRoot
func (_m *MockRepoConfigLoader) LoadRepoConfig(ctx context.Context, repoRoot string) (RepoConfig, error) {
	ret := _m.Called(ctx, repoRoot)

	if len(ret) == 0 {
		panic("no return value specified for LoadRepoConfig")
	}

	var r0 RepoConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (RepoConfig, error)); ok {
		return rf(ctx, repoRoot)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) RepoConfig); ok {
		r0 = rf(ctx, repoRoot)
	} else {
		r0 = ret.Get(0).(RepoConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repoRoot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepoConfigLoader_LoadRepoConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRepoConfig'
type MockRepoConfigLoader_LoadRepoConfig_Call struct {
	*mock.Call
}

// LoadRepoConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - repoRoot string
func (_e *MockRepoConfigLoader_Expecter) LoadRepoConfig(ctx interface{}, repoRoot interface{}) *MockRepoConfigLoader_LoadRepoConfig_Call {
	return &MockRepoConfigLoader_LoadRepoConfig_Call{Call: _e.mock.On("LoadRepoConfig", ctx, repoRoot)}
}

func (_c *MockRepoConfigLoader_LoadRepoConfig_Call) Run(run func(ctx context.Context, repoRoot string)) *MockRepoConfigLoader_LoadRepoConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepoConfigLoader_LoadRepoConfig_Call) Return(_a0 RepoConfig, _a1 error) *MockRepoConfigLoader_LoadRepoConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepoConfigLoader_LoadRepoConfig_Call) RunAndReturn(run func(context.Context, string) (RepoConfig, error)) *MockRepoConfigLoader_LoadRepoConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepoConfigLoader creates a new instance of MockRepoConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoConfigLoader {
	mock := &MockRepoConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
