// Code generated by mockery. DO NOT EDIT.

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockProviderClient is an autogenerated mock type for the ProviderClient type
type MockProviderClient struct {
	mock.Mock
}

type MockProviderClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderClient) EXPECT() *MockProviderClient_Expecter {
	return &MockProviderClient_Expecter{mock: &_m.Mock}
}

// DetectRuntimeState provides a mock function with given fields: snapshot
func (_m *MockProviderClient) DetectRuntimeState(snapshot RuntimeSnapshot) RuntimeState {
	ret := _m.Called(snapshot)

	if len(ret) == 0 {
		panic("no return value specified for DetectRuntimeState")
	}

	var r0 RuntimeState
	if rf, ok := ret.Get(0).(func(RuntimeSnapshot) RuntimeState); ok {
		r0 = rf(snapshot)
	} else {
		r0 = ret.Get(0).(RuntimeState)
	}

	return r0
}

// MockProviderClient_DetectRuntimeState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectRuntimeState'
type MockProviderClient_DetectRuntimeState_Call struct {
	*mock.Call
}

// DetectRuntimeState is a helper method to define mock.On call
//   - snapshot RuntimeSnapshot
func (_e *MockProviderClient_Expecter) DetectRuntimeState(snapshot interface{}) *MockProviderClient_DetectRuntimeState_Call {
	return &MockProviderClient_DetectRuntimeState_Call{Call: _e.mock.On("DetectRuntimeState", snapshot)}
}

func (_c *MockProviderClient_DetectRuntimeState_Call) Run(run func(snapshot RuntimeSnapshot)) *MockProviderClient_DetectRuntimeState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(RuntimeSnapshot))
	})
	return _c
}

func (_c *MockProviderClient_DetectRuntimeState_Call) Return(_a0 RuntimeState) *MockProviderClient_DetectRuntimeState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProviderClient_DetectRuntimeState_Call) RunAndReturn(run func(RuntimeSnapshot) RuntimeState) *MockProviderClient_DetectRuntimeState_Call {
	_c.Call.Return(run)
	return _c
}

// IsAvailable provides a mock function with given fields: ctx
func (_m *MockProviderClient) IsAvailable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsAvailable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProviderClient_IsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailable'
type MockProviderClient_IsAvailable_Call struct {
	*mock.Call
}

// IsAvailable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProviderClient_Expecter) IsAvailable(ctx interface{}) *MockProviderClient_IsAvailable_Call {
	return &MockProviderClient_IsAvailable_Call{Call: _e.mock.On("IsAvailable", ctx)}
}

func (_c *MockProviderClient_IsAvailable_Call) Run(run func(ctx context.Context)) *MockProviderClient_IsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProviderClient_IsAvailable_Call) Return(_a0 error) *MockProviderClient_IsAvailable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProviderClient_IsAvailable_Call) RunAndReturn(run func(context.Context) error) *MockProviderClient_IsAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// LaunchRequest provides a mock function with given fields: task
func (_m *MockProviderClient) LaunchRequest(task *Task) (LaunchRequest, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for LaunchRequest")
	}

	var r0 LaunchRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(*Task) (LaunchRequest, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(*Task) LaunchRequest); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Get(0).(LaunchRequest)
	}

	if rf, ok := ret.Get(1).(func(*Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderClient_LaunchRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LaunchRequest'
type MockProviderClient_LaunchRequest_Call struct {
	*mock.Call
}

// LaunchRequest is a helper method to define mock.On call
//   - task *Task
func (_e *MockProviderClient_Expecter) LaunchRequest(task interface{}) *MockProviderClient_LaunchRequest_Call {
	return &MockProviderClient_LaunchRequest_Call{Call: _e.mock.On("LaunchRequest", task)}
}

func (_c *MockProviderClient_LaunchRequest_Call) Run(run func(task *Task)) *MockProviderClient_LaunchRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Task))
	})
	return _c
}

func (_c *MockProviderClient_LaunchRequest_Call) Return(_a0 LaunchRequest, _a1 error) *MockProviderClient_LaunchRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderClient_LaunchRequest_Call) RunAndReturn(run func(*Task) (LaunchRequest, error)) *MockProviderClient_LaunchRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestTaskName provides a mock function with given fields: ctx, prompt
func (_m *MockProviderClient) SuggestTaskName(ctx context.Context, prompt string) (string, error) {
	ret := _m.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for SuggestTaskName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, prompt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, prompt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderClient_SuggestTaskName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestTaskName'
type MockProviderClient_SuggestTaskName_Call struct {
	*mock.Call
}

// SuggestTaskName is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockProviderClient_Expecter) SuggestTaskName(ctx interface{}, prompt interface{}) *MockProviderClient_SuggestTaskName_Call {
	return &MockProviderClient_SuggestTaskName_Call{Call: _e.mock.On("SuggestTaskName", ctx, prompt)}
}

func (_c *MockProviderClient_SuggestTaskName_Call) Run(run func(ctx context.Context, prompt string)) *MockProviderClient_SuggestTaskName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProviderClient_SuggestTaskName_Call) Return(_a0 string, _a1 error) *MockProviderClient_SuggestTaskName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderClient_SuggestTaskName_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockProviderClient_SuggestTaskName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProviderClient creates a new instance of MockProviderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderClient {
	mock := &MockProviderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
