// Code generated by mockery. DO NOT EDIT.

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// AppendEvent provides a mock function with given fields: ctx, taskID, eventType, payload
func (_m *MockTaskRepository) AppendEvent(ctx context.Context, taskID string, eventType string, payload string) error {
	ret := _m.Called(ctx, taskID, eventType, payload)

	if len(ret) == 0 {
		panic("no return value specified for AppendEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, taskID, eventType, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_AppendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendEvent'
type MockTaskRepository_AppendEvent_Call struct {
	*mock.Call
}

// AppendEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - eventType string
//   - payload string
func (_e *MockTaskRepository_Expecter) AppendEvent(ctx interface{}, taskID interface{}, eventType interface{}, payload interface{}) *MockTaskRepository_AppendEvent_Call {
	return &MockTaskRepository_AppendEvent_Call{Call: _e.mock.On("AppendEvent", ctx, taskID, eventType, payload)}
}

func (_c *MockTaskRepository_AppendEvent_Call) Run(run func(ctx context.Context, taskID string, eventType string, payload string)) *MockTaskRepository_AppendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTaskRepository_AppendEvent_Call) Return(_a0 error) *MockTaskRepository_AppendEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_AppendEvent_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockTaskRepository_AppendEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *MockTaskRepository) CreateTask(ctx context.Context, task *Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskRepository_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *Task
func (_e *MockTaskRepository_Expecter) CreateTask(ctx interface{}, task interface{}) *MockTaskRepository_CreateTask_Call {
	return &MockTaskRepository_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *MockTaskRepository_CreateTask_Call) Run(run func(ctx context.Context, task *Task)) *MockTaskRepository_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Task))
	})
	return _c
}

func (_c *MockTaskRepository_CreateTask_Call) Return(_a0 error) *MockTaskRepository_CreateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_CreateTask_Call) RunAndReturn(run func(context.Context, *Task) error) *MockTaskRepository_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, idOrSlug
func (_m *MockTaskRepository) GetTask(ctx context.Context, idOrSlug string) (*Task, error) {
	ret := _m.Called(ctx, idOrSlug)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Task, error)); ok {
		return rf(ctx, idOrSlug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Task); ok {
		r0 = rf(ctx, idOrSlug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idOrSlug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockTaskRepository_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - idOrSlug string
func (_e *MockTaskRepository_Expecter) GetTask(ctx interface{}, idOrSlug interface{}) *MockTaskRepository_GetTask_Call {
	return &MockTaskRepository_GetTask_Call{Call: _e.mock.On("GetTask", ctx, idOrSlug)}
}

func (_c *MockTaskRepository_GetTask_Call) Run(run func(ctx context.Context, idOrSlug string)) *MockTaskRepository_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskRepository_GetTask_Call) Return(_a0 *Task, _a1 error) *MockTaskRepository_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetTask_Call) RunAndReturn(run func(context.Context, string) (*Task, error)) *MockTaskRepository_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// IsAvailable provides a mock function with given fields: ctx
func (_m *MockTaskRepository) IsAvailable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsAvailable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_IsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailable'
type MockTaskRepository_IsAvailable_Call struct {
	*mock.Call
}

// IsAvailable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskRepository_Expecter) IsAvailable(ctx interface{}) *MockTaskRepository_IsAvailable_Call {
	return &MockTaskRepository_IsAvailable_Call{Call: _e.mock.On("IsAvailable", ctx)}
}

func (_c *MockTaskRepository_IsAvailable_Call) Run(run func(ctx context.Context)) *MockTaskRepository_IsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskRepository_IsAvailable_Call) Return(_a0 error) *MockTaskRepository_IsAvailable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_IsAvailable_Call) RunAndReturn(run func(context.Context) error) *MockTaskRepository_IsAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx
func (_m *MockTaskRepository) ListTasks(ctx context.Context) ([]*Task, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []*Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*Task, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*Task); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockTaskRepository_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskRepository_Expecter) ListTasks(ctx interface{}) *MockTaskRepository_ListTasks_Call {
	return &MockTaskRepository_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx)}
}

func (_c *MockTaskRepository_ListTasks_Call) Run(run func(ctx context.Context)) *MockTaskRepository_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskRepository_ListTasks_Call) Return(_a0 []*Task, _a1 error) *MockTaskRepository_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_ListTasks_Call) RunAndReturn(run func(context.Context) ([]*Task, error)) *MockTaskRepository_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: ctx, task
func (_m *MockTaskRepository) UpdateTask(ctx context.Context, task *Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskRepository_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *Task
func (_e *MockTaskRepository_Expecter) UpdateTask(ctx interface{}, task interface{}) *MockTaskRepository_UpdateTask_Call {
	return &MockTaskRepository_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, task)}
}

func (_c *MockTaskRepository_UpdateTask_Call) Run(run func(ctx context.Context, task *Task)) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Task))
	})
	return _c
}

func (_c *MockTaskRepository_UpdateTask_Call) Return(_a0 error) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_UpdateTask_Call) RunAndReturn(run func(context.Context, *Task) error) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
