// Code generated by mockery. DO NOT EDIT.

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionClient is an autogenerated mock type for the SessionClient type
type MockSessionClient struct {
	mock.Mock
}

type MockSessionClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionClient) EXPECT() *MockSessionClient_Expecter {
	return &MockSessionClient_Expecter{mock: &_m.Mock}
}

// DeleteTaskSession provides a mock function with given fields: ctx, task
func (_m *MockSessionClient) DeleteTaskSession(ctx context.Context, task *Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionClient_DeleteTaskSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTaskSession'
type MockSessionClient_DeleteTaskSession_Call struct {
	*mock.Call
}

// DeleteTaskSession is a helper method to define mock.On call
//   - ctx context.Context
//   - task *Task
func (_e *MockSessionClient_Expecter) DeleteTaskSession(ctx interface{}, task interface{}) *MockSessionClient_DeleteTaskSession_Call {
	return &MockSessionClient_DeleteTaskSession_Call{Call: _e.mock.On("DeleteTaskSession", ctx, task)}
}

func (_c *MockSessionClient_DeleteTaskSession_Call) Run(run func(ctx context.Context, task *Task)) *MockSessionClient_DeleteTaskSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Task))
	})
	return _c
}

func (_c *MockSessionClient_DeleteTaskSession_Call) Return(_a0 error) *MockSessionClient_DeleteTaskSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionClient_DeleteTaskSession_Call) RunAndReturn(run func(context.Context, *Task) error) *MockSessionClient_DeleteTaskSession_Call {
	_c.Call.Return(run)
	return _c
}

// InspectTaskSession provides a mock function with given fields: ctx, task
func (_m *MockSessionClient) InspectTaskSession(ctx context.Context, task *Task) (SessionResources, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for InspectTaskSession")
	}

	var r0 SessionResources
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *Task) (SessionResources, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *Task) SessionResources); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Get(0).(SessionResources)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionClient_InspectTaskSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InspectTaskSession'
type MockSessionClient_InspectTaskSession_Call struct {
	*mock.Call
}

// InspectTaskSession is a helper method to define mock.On call
//   - ctx context.Context
//   - task *Task
func (_e *MockSessionClient_Expecter) InspectTaskSession(ctx interface{}, task interface{}) *MockSessionClient_InspectTaskSession_Call {
	return &MockSessionClient_InspectTaskSession_Call{Call: _e.mock.On("InspectTaskSession", ctx, task)}
}

func (_c *MockSessionClient_InspectTaskSession_Call) Run(run func(ctx context.Context, task *Task)) *MockSessionClient_InspectTaskSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Task))
	})
	return _c
}

func (_c *MockSessionClient_InspectTaskSession_Call) Return(_a0 SessionResources, _a1 error) *MockSessionClient_InspectTaskSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionClient_InspectTaskSession_Call) RunAndReturn(run func(context.Context, *Task) (SessionResources, error)) *MockSessionClient_InspectTaskSession_Call {
	_c.Call.Return(run)
	return _c
}

// IsAvailable provides a mock function with given fields: ctx
func (_m *MockSessionClient) IsAvailable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsAvailable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionClient_IsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailable'
type MockSessionClient_IsAvailable_Call struct {
	*mock.Call
}

// IsAvailable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionClient_Expecter) IsAvailable(ctx interface{}) *MockSessionClient_IsAvailable_Call {
	return &MockSessionClient_IsAvailable_Call{Call: _e.mock.On("IsAvailable", ctx)}
}

func (_c *MockSessionClient_IsAvailable_Call) Run(run func(ctx context.Context)) *MockSessionClient_IsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSessionClient_IsAvailable_Call) Return(_a0 error) *MockSessionClient_IsAvailable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionClient_IsAvailable_Call) RunAndReturn(run func(context.Context) error) *MockSessionClient_IsAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// OpenTaskSession provides a mock function with given fields: ctx, task
func (_m *MockSessionClient) OpenTaskSession(ctx context.Context, task *Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for OpenTaskSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionClient_OpenTaskSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenTaskSession'
type MockSessionClient_OpenTaskSession_Call struct {
	*mock.Call
}

// OpenTaskSession is a helper method to define mock.On call
//   - ctx context.Context
//   - task *Task
func (_e *MockSessionClient_Expecter) OpenTaskSession(ctx interface{}, task interface{}) *MockSessionClient_OpenTaskSession_Call {
	return &MockSessionClient_OpenTaskSession_Call{Call: _e.mock.On("OpenTaskSession", ctx, task)}
}

func (_c *MockSessionClient_OpenTaskSession_Call) Run(run func(ctx context.Context, task *Task)) *MockSessionClient_OpenTaskSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Task))
	})
	return _c
}

func (_c *MockSessionClient_OpenTaskSession_Call) Return(_a0 error) *MockSessionClient_OpenTaskSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionClient_OpenTaskSession_Call) RunAndReturn(run func(context.Context, *Task) error) *MockSessionClient_OpenTaskSession_Call {
	_c.Call.Return(run)
	return _c
}

// SnapshotTaskSession provides a mock function with given fields: ctx, task
func (_m *MockSessionClient) SnapshotTaskSession(ctx context.Context, task *Task) (RuntimeSnapshot, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for SnapshotTaskSession")
	}

	var r0 RuntimeSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *Task) (RuntimeSnapshot, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *Task) RuntimeSnapshot); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Get(0).(RuntimeSnapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionClient_SnapshotTaskSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SnapshotTaskSession'
type MockSessionClient_SnapshotTaskSession_Call struct {
	*mock.Call
}

// SnapshotTaskSession is a helper method to define mock.On call
//   - ctx context.Context
//   - task *Task
func (_e *MockSessionClient_Expecter) SnapshotTaskSession(ctx interface{}, task interface{}) *MockSessionClient_SnapshotTaskSession_Call {
	return &MockSessionClient_SnapshotTaskSession_Call{Call: _e.mock.On("SnapshotTaskSession", ctx, task)}
}

func (_c *MockSessionClient_SnapshotTaskSession_Call) Run(run func(ctx context.Context, task *Task)) *MockSessionClient_SnapshotTaskSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Task))
	})
	return _c
}

func (_c *MockSessionClient_SnapshotTaskSession_Call) Return(_a0 RuntimeSnapshot, _a1 error) *MockSessionClient_SnapshotTaskSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionClient_SnapshotTaskSession_Call) RunAndReturn(run func(context.Context, *Task) (RuntimeSnapshot, error)) *MockSessionClient_SnapshotTaskSession_Call {
	_c.Call.Return(run)
	return _c
}

// StartTaskSession provides a mock function with given fields: ctx, task, launch
func (_m *MockSessionClient) StartTaskSession(ctx context.Context, task *Task, launch LaunchRequest) error {
	ret := _m.Called(ctx, task, launch)

	if len(ret) == 0 {
		panic("no return value specified for StartTaskSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Task, LaunchRequest) error); ok {
		r0 = rf(ctx, task, launch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionClient_StartTaskSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTaskSession'
type MockSessionClient_StartTaskSession_Call struct {
	*mock.Call
}

// StartTaskSession is a helper method to define mock.On call
//   - ctx context.Context
//   - task *Task
//   - launch LaunchRequest
func (_e *MockSessionClient_Expecter) StartTaskSession(ctx interface{}, task interface{}, launch interface{}) *MockSessionClient_StartTaskSession_Call {
	return &MockSessionClient_StartTaskSession_Call{Call: _e.mock.On("StartTaskSession", ctx, task, launch)}
}

func (_c *MockSessionClient_StartTaskSession_Call) Run(run func(ctx context.Context, task *Task, launch LaunchRequest)) *MockSessionClient_StartTaskSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Task), args[2].(LaunchRequest))
	})
	return _c
}

func (_c *MockSessionClient_StartTaskSession_Call) Return(_a0 error) *MockSessionClient_StartTaskSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionClient_StartTaskSession_Call) RunAndReturn(run func(context.Context, *Task, LaunchRequest) error) *MockSessionClient_StartTaskSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionClient creates a new instance of MockSessionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionClient {
	mock := &MockSessionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
