// Code generated by mockery. DO NOT EDIT.

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepoClient is an autogenerated mock type for the RepoClient type
type MockRepoClient struct {
	mock.Mock
}

type MockRepoClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoClient) EXPECT() *MockRepoClient_Expecter {
	return &MockRepoClient_Expecter{mock: &_m.Mock}
}

// CreateTaskWorkspace provides a mock function with given fields: ctx, task
func (_m *MockRepoClient) CreateTaskWorkspace(ctx context.Context, task *Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTaskWorkspace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepoClient_CreateTaskWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTaskWorkspace'
type MockRepoClient_CreateTaskWorkspace_Call struct {
	*mock.Call
}

// CreateTaskWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - task *Task
func (_e *MockRepoClient_Expecter) CreateTaskWorkspace(ctx interface{}, task interface{}) *MockRepoClient_CreateTaskWorkspace_Call {
	return &MockRepoClient_CreateTaskWorkspace_Call{Call: _e.mock.On("CreateTaskWorkspace", ctx, task)}
}

func (_c *MockRepoClient_CreateTaskWorkspace_Call) Run(run func(ctx context.Context, task *Task)) *MockRepoClient_CreateTaskWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Task))
	})
	return _c
}

func (_c *MockRepoClient_CreateTaskWorkspace_Call) Return(_a0 error) *MockRepoClient_CreateTaskWorkspace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepoClient_CreateTaskWorkspace_Call) RunAndReturn(run func(context.Context, *Task) error) *MockRepoClient_CreateTaskWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// DetectRepo provides a mock function with given fields: ctx, cwd
func (_m *MockRepoClient) DetectRepo(ctx context.Context, cwd string) (RepoContext, error) {
	ret := _m.Called(ctx, cwd)

	if len(ret) == 0 {
		panic("no return value specified for DetectRepo")
	}

	var r0 RepoContext
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (RepoContext, error)); ok {
		return rf(ctx, cwd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) RepoContext); ok {
		r0 = rf(ctx, cwd)
	} else {
		r0 = ret.Get(0).(RepoContext)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cwd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepoClient_DetectRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectRepo'
type MockRepoClient_DetectRepo_Call struct {
	*mock.Call
}

// DetectRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - cwd string
func (_e *MockRepoClient_Expecter) DetectRepo(ctx interface{}, cwd interface{}) *MockRepoClient_DetectRepo_Call {
	return &MockRepoClient_DetectRepo_Call{Call: _e.mock.On("DetectRepo", ctx, cwd)}
}

func (_c *MockRepoClient_DetectRepo_Call) Run(run func(ctx context.Context, cwd string)) *MockRepoClient_DetectRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepoClient_DetectRepo_Call) Return(_a0 RepoContext, _a1 error) *MockRepoClient_DetectRepo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepoClient_DetectRepo_Call) RunAndReturn(run func(context.Context, string) (RepoContext, error)) *MockRepoClient_DetectRepo_Call {
	_c.Call.Return(run)
	return _c
}

// InspectTaskWorkspace provides a mock function with given fields: ctx, task
func (_m *MockRepoClient) InspectTaskWorkspace(ctx context.Context, task *Task) (RepoResources, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for InspectTaskWorkspace")
	}

	var r0 RepoResources
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *Task) (RepoResources, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *Task) RepoResources); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Get(0).(RepoResources)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepoClient_InspectTaskWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InspectTaskWorkspace'
type MockRepoClient_InspectTaskWorkspace_Call struct {
	*mock.Call
}

// InspectTaskWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - task *Task
func (_e *MockRepoClient_Expecter) InspectTaskWorkspace(ctx interface{}, task interface{}) *MockRepoClient_InspectTaskWorkspace_Call {
	return &MockRepoClient_InspectTaskWorkspace_Call{Call: _e.mock.On("InspectTaskWorkspace", ctx, task)}
}

func (_c *MockRepoClient_InspectTaskWorkspace_Call) Run(run func(ctx context.Context, task *Task)) *MockRepoClient_InspectTaskWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Task))
	})
	return _c
}

func (_c *MockRepoClient_InspectTaskWorkspace_Call) Return(_a0 RepoResources, _a1 error) *MockRepoClient_InspectTaskWorkspace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepoClient_InspectTaskWorkspace_Call) RunAndReturn(run func(context.Context, *Task) (RepoResources, error)) *MockRepoClient_InspectTaskWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// IsAvailable provides a mock function with given fields: ctx
func (_m *MockRepoClient) IsAvailable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsAvailable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepoClient_IsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailable'
type MockRepoClient_IsAvailable_Call struct {
	*mock.Call
}

// IsAvailable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepoClient_Expecter) IsAvailable(ctx interface{}) *MockRepoClient_IsAvailable_Call {
	return &MockRepoClient_IsAvailable_Call{Call: _e.mock.On("IsAvailable", ctx)}
}

func (_c *MockRepoClient_IsAvailable_Call) Run(run func(ctx context.Context)) *MockRepoClient_IsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepoClient_IsAvailable_Call) Return(_a0 error) *MockRepoClient_IsAvailable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepoClient_IsAvailable_Call) RunAndReturn(run func(context.Context) error) *MockRepoClient_IsAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTaskWorkspace provides a mock function with given fields: ctx, task
func (_m *MockRepoClient) RemoveTaskWorkspace(ctx context.Context, task *Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTaskWorkspace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepoClient_RemoveTaskWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTaskWorkspace'
type MockRepoClient_RemoveTaskWorkspace_Call struct {
	*mock.Call
}

// RemoveTaskWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - task *Task
func (_e *MockRepoClient_Expecter) RemoveTaskWorkspace(ctx interface{}, task interface{}) *MockRepoClient_RemoveTaskWorkspace_Call {
	return &MockRepoClient_RemoveTaskWorkspace_Call{Call: _e.mock.On("RemoveTaskWorkspace", ctx, task)}
}

func (_c *MockRepoClient_RemoveTaskWorkspace_Call) Run(run func(ctx context.Context, task *Task)) *MockRepoClient_RemoveTaskWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Task))
	})
	return _c
}

func (_c *MockRepoClient_RemoveTaskWorkspace_Call) Return(_a0 error) *MockRepoClient_RemoveTaskWorkspace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepoClient_RemoveTaskWorkspace_Call) RunAndReturn(run func(context.Context, *Task) error) *MockRepoClient_RemoveTaskWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepoClient creates a new instance of MockRepoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoClient {
	mock := &MockRepoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
