// Code generated by mockery. DO NOT EDIT.

package cli

import (
	core "agent/internal/core"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// CreateTaskWithProgress provides a mock function with given fields: ctx, input, options, progress
func (_m *MockTaskService) CreateTaskWithProgress(ctx context.Context, input core.NewTaskInput, options core.CreateTaskOptions, progress func(core.TaskProgress)) (*core.Task, error) {
	ret := _m.Called(ctx, input, options, progress)

	if len(ret) == 0 {
		panic("no return value specified for CreateTaskWithProgress")
	}

	var r0 *core.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.NewTaskInput, core.CreateTaskOptions, func(core.TaskProgress)) (*core.Task, error)); ok {
		return rf(ctx, input, options, progress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.NewTaskInput, core.CreateTaskOptions, func(core.TaskProgress)) *core.Task); ok {
		r0 = rf(ctx, input, options, progress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.NewTaskInput, core.CreateTaskOptions, func(core.TaskProgress)) error); ok {
		r1 = rf(ctx, input, options, progress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_CreateTaskWithProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTaskWithProgress'
type MockTaskService_CreateTaskWithProgress_Call struct {
	*mock.Call
}

// CreateTaskWithProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - input core.NewTaskInput
//   - options core.CreateTaskOptions
//   - progress func(core.TaskProgress)
func (_e *MockTaskService_Expecter) CreateTaskWithProgress(ctx interface{}, input interface{}, options interface{}, progress interface{}) *MockTaskService_CreateTaskWithProgress_Call {
	return &MockTaskService_CreateTaskWithProgress_Call{Call: _e.mock.On("CreateTaskWithProgress", ctx, input, options, progress)}
}

func (_c *MockTaskService_CreateTaskWithProgress_Call) Run(run func(ctx context.Context, input core.NewTaskInput, options core.CreateTaskOptions, progress func(core.TaskProgress))) *MockTaskService_CreateTaskWithProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.NewTaskInput), args[2].(core.CreateTaskOptions), args[3].(func(core.TaskProgress)))
	})
	return _c
}

func (_c *MockTaskService_CreateTaskWithProgress_Call) Return(_a0 *core.Task, _a1 error) *MockTaskService_CreateTaskWithProgress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_CreateTaskWithProgress_Call) RunAndReturn(run func(context.Context, core.NewTaskInput, core.CreateTaskOptions, func(core.TaskProgress)) (*core.Task, error)) *MockTaskService_CreateTaskWithProgress_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTaskResources provides a mock function with given fields: ctx, idOrSlug
func (_m *MockTaskService) DeleteTaskResources(ctx context.Context, idOrSlug string) (*core.Task, error) {
	ret := _m.Called(ctx, idOrSlug)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskResources")
	}

	var r0 *core.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*core.Task, error)); ok {
		return rf(ctx, idOrSlug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *core.Task); ok {
		r0 = rf(ctx, idOrSlug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idOrSlug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_DeleteTaskResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTaskResources'
type MockTaskService_DeleteTaskResources_Call struct {
	*mock.Call
}

// DeleteTaskResources is a helper method to define mock.On call
//   - ctx context.Context
//   - idOrSlug string
func (_e *MockTaskService_Expecter) DeleteTaskResources(ctx interface{}, idOrSlug interface{}) *MockTaskService_DeleteTaskResources_Call {
	return &MockTaskService_DeleteTaskResources_Call{Call: _e.mock.On("DeleteTaskResources", ctx, idOrSlug)}
}

func (_c *MockTaskService_DeleteTaskResources_Call) Run(run func(ctx context.Context, idOrSlug string)) *MockTaskService_DeleteTaskResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_DeleteTaskResources_Call) Return(_a0 *core.Task, _a1 error) *MockTaskService_DeleteTaskResources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_DeleteTaskResources_Call) RunAndReturn(run func(context.Context, string) (*core.Task, error)) *MockTaskService_DeleteTaskResources_Call {
	_c.Call.Return(run)
	return _c
}

// Doctor provides a mock function with given fields: ctx, cwd
func (_m *MockTaskService) Doctor(ctx context.Context, cwd string) (core.DoctorResult, error) {
	ret := _m.Called(ctx, cwd)

	if len(ret) == 0 {
		panic("no return value specified for Doctor")
	}

	var r0 core.DoctorResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (core.DoctorResult, error)); ok {
		return rf(ctx, cwd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) core.DoctorResult); ok {
		r0 = rf(ctx, cwd)
	} else {
		r0 = ret.Get(0).(core.DoctorResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cwd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_Doctor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Doctor'
type MockTaskService_Doctor_Call struct {
	*mock.Call
}

// Doctor is a helper method to define mock.On call
//   - ctx context.Context
//   - cwd string
func (_e *MockTaskService_Expecter) Doctor(ctx interface{}, cwd interface{}) *MockTaskService_Doctor_Call {
	return &MockTaskService_Doctor_Call{Call: _e.mock.On("Doctor", ctx, cwd)}
}

func (_c *MockTaskService_Doctor_Call) Run(run func(ctx context.Context, cwd string)) *MockTaskService_Doctor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_Doctor_Call) Return(_a0 core.DoctorResult, _a1 error) *MockTaskService_Doctor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_Doctor_Call) RunAndReturn(run func(context.Context, string) (core.DoctorResult, error)) *MockTaskService_Doctor_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskHookEvents provides a mock function with given fields: ctx, taskID, limit
func (_m *MockTaskService) GetTaskHookEvents(ctx context.Context, taskID string, limit int) ([]core.HookEvent, error) {
	ret := _m.Called(ctx, taskID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskHookEvents")
	}

	var r0 []core.HookEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]core.HookEvent, error)); ok {
		return rf(ctx, taskID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []core.HookEvent); ok {
		r0 = rf(ctx, taskID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.HookEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, taskID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_GetTaskHookEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskHookEvents'
type MockTaskService_GetTaskHookEvents_Call struct {
	*mock.Call
}

// GetTaskHookEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - limit int
func (_e *MockTaskService_Expecter) GetTaskHookEvents(ctx interface{}, taskID interface{}, limit interface{}) *MockTaskService_GetTaskHookEvents_Call {
	return &MockTaskService_GetTaskHookEvents_Call{Call: _e.mock.On("GetTaskHookEvents", ctx, taskID, limit)}
}

func (_c *MockTaskService_GetTaskHookEvents_Call) Run(run func(ctx context.Context, taskID string, limit int)) *MockTaskService_GetTaskHookEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockTaskService_GetTaskHookEvents_Call) Return(_a0 []core.HookEvent, _a1 error) *MockTaskService_GetTaskHookEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_GetTaskHookEvents_Call) RunAndReturn(run func(context.Context, string, int) ([]core.HookEvent, error)) *MockTaskService_GetTaskHookEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx
func (_m *MockTaskService) ListTasks(ctx context.Context) ([]*core.Task, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []*core.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*core.Task, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*core.Task); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockTaskService_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskService_Expecter) ListTasks(ctx interface{}) *MockTaskService_ListTasks_Call {
	return &MockTaskService_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx)}
}

func (_c *MockTaskService_ListTasks_Call) Run(run func(ctx context.Context)) *MockTaskService_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskService_ListTasks_Call) Return(_a0 []*core.Task, _a1 error) *MockTaskService_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_ListTasks_Call) RunAndReturn(run func(context.Context) ([]*core.Task, error)) *MockTaskService_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// ListTaskViews provides a mock function with given fields: ctx
func (_m *MockTaskService) ListTaskViews(ctx context.Context) ([]*core.TaskView, error) {
	if !hasExpectedCall(&_m.Mock, "ListTaskViews") && hasExpectedCall(&_m.Mock, "ListTasks") {
		tasks, err := _m.ListTasks(ctx)
		if err != nil {
			return nil, err
		}

		views := make([]*core.TaskView, 0, len(tasks))
		for _, task := range tasks {
			views = append(views, &core.TaskView{Task: task})
		}

		return views, nil
	}

	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTaskViews")
	}

	var r0 []*core.TaskView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*core.TaskView, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*core.TaskView); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.TaskView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_ListTaskViews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTaskViews'
type MockTaskService_ListTaskViews_Call struct {
	*mock.Call
}

// ListTaskViews is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskService_Expecter) ListTaskViews(ctx interface{}) *MockTaskService_ListTaskViews_Call {
	return &MockTaskService_ListTaskViews_Call{Call: _e.mock.On("ListTaskViews", ctx)}
}

func (_c *MockTaskService_ListTaskViews_Call) Run(run func(ctx context.Context)) *MockTaskService_ListTaskViews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskService_ListTaskViews_Call) Return(_a0 []*core.TaskView, _a1 error) *MockTaskService_ListTaskViews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_ListTaskViews_Call) RunAndReturn(run func(context.Context) ([]*core.TaskView, error)) *MockTaskService_ListTaskViews_Call {
	_c.Call.Return(run)
	return _c
}

// OpenTask provides a mock function with given fields: ctx, idOrSlug
func (_m *MockTaskService) OpenTask(ctx context.Context, idOrSlug string) error {
	ret := _m.Called(ctx, idOrSlug)

	if len(ret) == 0 {
		panic("no return value specified for OpenTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, idOrSlug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_OpenTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenTask'
type MockTaskService_OpenTask_Call struct {
	*mock.Call
}

// OpenTask is a helper method to define mock.On call
//   - ctx context.Context
//   - idOrSlug string
func (_e *MockTaskService_Expecter) OpenTask(ctx interface{}, idOrSlug interface{}) *MockTaskService_OpenTask_Call {
	return &MockTaskService_OpenTask_Call{Call: _e.mock.On("OpenTask", ctx, idOrSlug)}
}

func (_c *MockTaskService_OpenTask_Call) Run(run func(ctx context.Context, idOrSlug string)) *MockTaskService_OpenTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_OpenTask_Call) Return(_a0 error) *MockTaskService_OpenTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_OpenTask_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskService_OpenTask_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestTaskName provides a mock function with given fields: ctx, prompt, provider
func (_m *MockTaskService) SuggestTaskName(ctx context.Context, prompt string, provider string) (string, error) {
	ret := _m.Called(ctx, prompt, provider)

	if len(ret) == 0 {
		panic("no return value specified for SuggestTaskName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, prompt, provider)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, prompt, provider)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, prompt, provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_SuggestTaskName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestTaskName'
type MockTaskService_SuggestTaskName_Call struct {
	*mock.Call
}

// SuggestTaskName is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
//   - provider string
func (_e *MockTaskService_Expecter) SuggestTaskName(ctx interface{}, prompt interface{}, provider interface{}) *MockTaskService_SuggestTaskName_Call {
	return &MockTaskService_SuggestTaskName_Call{Call: _e.mock.On("SuggestTaskName", ctx, prompt, provider)}
}

func (_c *MockTaskService_SuggestTaskName_Call) Run(run func(ctx context.Context, prompt string, provider string)) *MockTaskService_SuggestTaskName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTaskService_SuggestTaskName_Call) Return(_a0 string, _a1 error) *MockTaskService_SuggestTaskName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_SuggestTaskName_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockTaskService_SuggestTaskName_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeTaskHookUpdates provides a mock function with given fields: ctx
func (_m *MockTaskService) SubscribeTaskHookUpdates(ctx context.Context) (<-chan core.HookSessionSummary, func(), error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeTaskHookUpdates")
	}

	var r0 <-chan core.HookSessionSummary
	var r1 func()
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan core.HookSessionSummary, func(), error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan core.HookSessionSummary); ok {
		r0 = rf(ctx)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(<-chan core.HookSessionSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context) func()); ok {
		r1 = rf(ctx)
	} else if ret.Get(1) != nil {
		r1 = ret.Get(1).(func())
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTaskService_SubscribeTaskHookUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeTaskHookUpdates'
type MockTaskService_SubscribeTaskHookUpdates_Call struct {
	*mock.Call
}

// SubscribeTaskHookUpdates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskService_Expecter) SubscribeTaskHookUpdates(ctx interface{}) *MockTaskService_SubscribeTaskHookUpdates_Call {
	return &MockTaskService_SubscribeTaskHookUpdates_Call{Call: _e.mock.On("SubscribeTaskHookUpdates", ctx)}
}

func (_c *MockTaskService_SubscribeTaskHookUpdates_Call) Run(run func(ctx context.Context)) *MockTaskService_SubscribeTaskHookUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskService_SubscribeTaskHookUpdates_Call) Return(_a0 <-chan core.HookSessionSummary, _a1 func(), _a2 error) *MockTaskService_SubscribeTaskHookUpdates_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTaskService_SubscribeTaskHookUpdates_Call) RunAndReturn(run func(context.Context) (<-chan core.HookSessionSummary, func(), error)) *MockTaskService_SubscribeTaskHookUpdates_Call {
	_c.Call.Return(run)
	return _c
}

func hasExpectedCall(m *mock.Mock, method string) bool {
	for _, call := range m.ExpectedCalls {
		if call.Method == method {
			return true
		}
	}

	return false
}

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
